Repository gitkraken/vscode-gitlens, pull requests merged in 2024-09, with the labels that each got.

#3524 Change GK account authentication to no longer use the VS Code authentication system
  src/plus/gk/account/authenticationProvider.ts
  src/plus/gk/account/subscriptionService.ts
Labels: feature

#3559 Refines 'Create Worktree' Flow
  src/commands/git/worktree.ts
  src/git/models/worktree.ts
Labels: area-worktrees

#3573 'Create Branch in Worktree' option in 'Create Branch' shows a repo picker if you have multiple repos open
  src/commands/git/branch.ts
Labels: bug, area-worktrees

#3612 Prevents cloud integration sync process from opening gkdev connect page/flow
  src/plus/integrations/authentication/integrationAuthentication.ts
  src/plus/integrations/integration.ts
Labels: bug, area-integrations

#3624 Adds debug commands and utilities to mock/restore subscription state
  package.json
  src/@types/global.d.ts
  src/constants.commands.ts
  src/constants.storage.ts
  src/plus/gk/account/__debug__accountDebug.ts
  src/plus/gk/account/subscriptionService.ts
  src/plus/gk/checkin.ts
  src/plus/gk/utils.ts
  src/webviews/apps/shared/context.ts
  webpack.config.mjs
Labels: area-pro-account
